apiVersion: v1
kind: Secret
metadata:
  name: {{ include "raucle-gateway.fullname" . }}-secrets
  labels:
    {{- include "raucle-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  RAUCLE_ADMIN_KEY: {{ required "config.adminKey is REQUIRED" .Values.config.adminKey | quote }}
  {{- with .Values.config.demoKey }}
  RAUCLE_DEMO_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.healthKey }}
  RAUCLE_HEALTH_KEY: {{ . | quote }}
  {{- end }}
  {{- if .Values.siem.enabled }}
  {{- with .Values.siem.token }}
  RAUCLE_SIEM_TOKEN: {{ . | quote }}
  {{- end }}
  {{- end }}
