apiVersion: v1
kind: Service
metadata:
  name: {{ include "raucle-gateway.fullname" . }}
  labels:
    {{- include "raucle-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
  selector:
    app.kubernetes.io/name: {{ include "raucle-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
